#!/bin/bash
#BSUB -J mm10_guide_test
#BSUB -n 1
#BSUB -R rusage[mem=100]
#BSUB -W 24:00
#BSUB -o %J.stdout
#BSUB -eo %J.stderr

# set up env, cd to source
annotations="/home/zamparol/projects/crisprML/data/annotations/mm10_exons_by_symbol_fol.bed"
infile="/data/leslie/zamparol/crisprML/kmers/mm10/Cas9/mm10_all_kmers.txt"
outdir="/data/leslie/zamparol/crisprML/results/gRNAs/mm10/"


cd ~/projects/crisprML/src

set +o nounset
source activate py2
python gRNA_from_annotations.py -a $annotations -i $infile -o $outdir
source deactivate
set -o nounset
