#!/bin/bash
#BSUB -J mm10_guides_OT_mm10
#BSUB -n 1
#BSUB -R rusage[mem=140]
#BSUB -W 6:00
#BSUB -o %J.stdout
#BSUB -eo %J.stderr


# dataset sgRNA fields
input="$INFILE"
outdir="$OUTDIR"
kmers="/data/leslie/zamparol/crisprML/kmers/mm10/Cas9/mm10_kmers.db"
trie="/data/leslie/zamparol/crisprML/tries/mm10_all_trie.dat"
mismatch="/data/leslie/zamparol/crisprML/CFD_scoring/mismatch_score.pkl"
pam="/data/leslie/zamparol/crisprML/CFD_scoring/pam_scores.pkl"


cd ~/projects/crisprML/src

# stage the kmers db
cp /data/leslie/zamparol/crisprML/kmers/mm10/Cas9/mm10_kmers.db /scratch/mm10_kmers.db
kmers_local=/scratch/mm10_kmers.db

set +o nounset
source activate py2
python specificity_score_distance_neighbors.py -i $input -o $outdir -k $kmers_local -t $trie -m $mismatch -p $pam
source deactivate
set -o nounset

# clean up scratch
rm /scratch/mm10_kmers.db
